plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nhm.feeders'
    compileSdk 34

    defaultConfig {
        applicationId "com.nhm.feeders"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.8.0'
    implementation 'androidx.core:core:1.13.1'
}
